SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Calendar_Days_Elapsed__c</fullName>
        <description>Number of calendar days when Goal was open or escalated</description>
        <inlineHelpText>Number of calendar days when Goal was open or escalated</inlineHelpText>
        <label>Calendar Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SLA requirement</description>
        <inlineHelpText>SLA requirement</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Working_Days_Elapsed__c</fullName>
        <description>Number of working days when the Case was opened or escalated</description>
        <inlineHelpText>Number of working days when the Case was opened or eesclated</inlineHelpText>
        <label>Working Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/SLA__c.object
<CustomObject>
    <description>A record of the available SLAs that can be applied to Goals and Tickets</description>
    <fields>
        <fullName>Customer_Acknowledgement_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If the SLA requires a customer acknowledgement within a certain number of days after commencement this should be specified here (0 for no acknowledgement required)</description>
        <inlineHelpText>If the SLA requires a customer acknowledgement within a certain number of days after commencement this should be specified here (0 for no acknowledgement required)</inlineHelpText>
        <label>Customer Acknowledgement (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Escalation_Prior_to_SLA_Breach_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If the record should be escalated a set number of days prior to SLA breach (assuming it hasn&apos;t already been escalated or closed) then specify the number of days before the SLA breach that the record should be escalated here. (0 = no auto escalation required)</description>
        <inlineHelpText>The number of days before the SLA breach that the record should be escalated here. (0 = escalation required)</inlineHelpText>
        <label>Escalation Prior to SLA Breach (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Length_Days__c</fullName>
        <description>The length of the SLA in days</description>
        <label>SLA Length (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 2 - Chidlren&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Children&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Adult&apos;s Social Care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Calendar_Days_Elapsed__c</fullName>
        <description>Number of calendar days during which the Ticket was opened or escalated</description>
        <inlineHelpText>Number of calendar days during which the Ticket was opened or escalated</inlineHelpText>
        <label>Calendar Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Working_Days_Elapsed__c</fullName>
        <description>Number of working days during which the Ticket was opened or escalated</description>
        <inlineHelpText>Number of working days during which the Ticket was opened or escalated</inlineHelpText>
        <label>Working Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/SLATestClass.cls
/*------------------------------------------------------------
Author:        Matt Urbanowski
Company:       Arcus Global Ltd
Date:          09/07/2013
Description:   Class containing all test classes for SLA-related apex and triggers
Test Class:    SLATestClass
------------------------------------------------------------*/
@isTest
public class SLATestClass {

    public static SLA__c CreateTestSLA() {
        SLA__c SLA = new SLA__c(Name = '40 working days TEST', Customer_Acknowledgement_Days__c = 3, Escalation_Prior_to_SLA_Breach_Days__c = 2, SLA_Length_Days__c = 40);
        insert SLA;
        return SLA;
    }

    private static void testCaseUpdateFails(Case myCase) {
        Boolean HasError = false;
        try {
            update myCase;
        } catch (DmlException e) {
            HasError=true;
            system.debug('**************** e.getMessage()= ' + e.getMessage());
        }
        //System.Assert(HasError);
        System.assertEquals(HasError, true);
    }
    
    private static void testTicketUpdateFails(Ticket__c myTicket) {
        Boolean HasError = false;
        try {
            update myTicket;
        } catch (DmlException e) {
            HasError=true;
        }
        System.Assert(HasError);
    }
	
	/**
    static TestMethod void testSLAGoalTicketPicklist() {
        Test.startTest();
        Case testCase = TestClass.CreateTestCase(TestClass.CreateTestContact(TestClass.CreateTestAccount()));
        Ticket__c testTicket = TestClass.CreateTestTicket(testCase);
        SLA__c SLA1 = CreateTestSLA();
        
        // TEST 1 - Test assigning unique valid SLA to case & ticket
        testCase.Active_SLA__c = '40 working days TEST';
        update testCase;
        testTicket.GLOBAL_Active_SLA__c = '40 working days TEST';
        update testTicket;
        
        // TEST 2 - Test assigning non-unique SLA to case
        SLA__c SLA2 = CreateTestSLA();
        testCaseUpdateFails(testCase);
        
        // TEST 3 - Test assigning non-unique SLA to ticket
        testTicketUpdateFails(testTicket);
        
        // TEST 4 - Assigning non-existent SLA to case
        testCase.Active_SLA__c = '80 working days TEST';
        testCaseUpdateFails(testCase);
        
        // TEST 5 - Assigning non-existent SLA to ticket
        testTicket.GLOBAL_Active_SLA__c = '80 working days TEST';
        testTicketUpdateFails(testTicket);
        
        Test.stopTest();
    }
    */

    static TestMethod void testSLATicketCounter() {
        Test.startTest();
        Ticket__c testTicket = TestClass.CreateTestTicket(TestClass.CreateTestCase(TestClass.CreateTestContact(TestClass.CreateTestAccount())));
        testTicket.GLOBAL_Working_Days_Elapsed__c = 1;
        testTicket.GLOBAL_Calendar_Days_Elapsed__c = 1;
        testTicket.GLOBAL_Ticket_Status__c = 'Open';
        update testTicket;
        SLATicketCounter batch = new SLATicketCounter();
        Database.executeBatch(batch);
        Test.stopTest();
    }
    
    static TestMethod void testSLAGoalCounter() {
        Test.startTest();
        Case testCase = TestClass.CreateTestCase(TestClass.CreateTestContact(TestClass.CreateTestAccount()));
        testCase.Working_Days_Elapsed__c = 1;
        testCase.Calendar_Days_Elapsed__c = 1;
        testCase.Status = 'Open';
        update testCase;
        SLAGoalCounter batch = new SLAGoalCounter();
        Database.executeBatch(batch);
        Test.stopTest();
    }

    // Test method for global SLA Functions class
    static TestMethod void testSLAFunctions()
    {
        Test.startTest();
        // Test add days
        Decimal i = 5;
        Decimal RetVal = SLAFunctions.Add1Day(i);
        System.Assert(RetVal == 6);
        
        // Test null day value
        i = null;
        RetVal = SLAFunctions.Add1Day(i);
        System.Assert(RetVal == 1);

        // Test yesterday is working day

        // Insert test holiday
        Holiday h = new Holiday(Name = 'Bank Holiday Monday', ActivityDate = Date.Today()-1);
        insert h;
        
        // Test yesterday is always a calendar day
        System.Assert(SLAFunctions.yesterdayCalendarDay()==true);
        
        // Test working day if yesterday was a holiday
        System.Assert(SLAFunctions.yesterdayWorkingDay()==false);
                
        Test.stopTest(); 
        
         
    }
   

}