SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>REP_Customer_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</description>
        <inlineHelpText>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Goals</relationshipLabel>
        <relationshipName>Representing</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer who has reported the case that this record is a child of</description>
        <inlineHelpText>The customer who has reported the case that this record is a child of</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer&apos;s representative (set on the case record)</description>
        <inlineHelpText>The customer&apos;s representative (set on the case record)</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Tickets</relationshipLabel>
        <relationshipName>Tickets_Acting_as_Representative_on</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/trigger_Case_Customer_Propogate.cls
/**
 * TODO (ANA): THIS CLASS IS TO BE DELETED, NO LONGER IN USE, HAS BEEN REFACTORED TO ANOTHER CLASS
 **/
/*------------------------------------------------------------
Author:        Douglas Guthrie
Company:       Arcus Global Ltd
Date:          31/07/2013
Description:   When a ticket is saved set the Customer and Representative
               Lookup fields equal to the goal lookups.     
Test Class:    TestClass
------------------------------------------------------------*/

public class trigger_Case_Customer_Propogate {
	
	/**    
    public trigger_Case_Customer_Propogate(Case myCase){
        System.debug('***** trigger_Case_Customer_Propogate'); 
        // get all the tickets that have that case as a parent
        System.debug(myCase);
        System.debug(myCase.id);
        
        List<Ticket__c> tickets = [SELECT Id, Name, GLOBAL_Customer__c, GLOBAL_Representative__c, GLOBAL_Goal__c FROM Ticket__c WHERE GLOBAL_Goal__c  =: myCase.id ];
        System.debug(tickets);
        
        //loop over the list of tickets and update each ticket record
        for (Integer i = 0; i < tickets.size(); i++) {
            tickets[i].GLOBAL_Representative__c = myCase.REP_Customer_Representative__c   ;
            tickets[i].GLOBAL_Customer__c = myCase.ContactId ;
        }
        
        System.debug(tickets);
        // update the database
        update tickets;
    } 
    */
}