SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Popular_Goals__c</fullName>
        <description>A list of popular goals that customers have</description>
        <inlineHelpText>The most frequent customers enquiries</inlineHelpText>
        <label>Top Enquiries</label>
        <picklist>
            <picklistValues>
                <fullName>Animal Warden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Badge/Freedom Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pest Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pollution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tidy Town</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waste Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other &gt;</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SLA requirement</description>
        <inlineHelpText>SLA requirement</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CCC</fullName>
        <active>true</active>
        <businessProcess>Goal Process</businessProcess>
        <description>A case as used by the Customer Contact Centre</description>
        <label>CCC</label>
    </recordTypes>
</CustomObject>

SourceMetaData/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user account that the contact is associated with</description>
        <inlineHelpText>The user account that the contact is associated with</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/ICT_Article__c.object
<CustomObject>
    <description>Articlein a Knowledge base to support the ICT Service Desk</description>
    <fields>
        <fullName>Article_Name__c</fullName>
        <label>Article Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <description>The Type of article that this record corresponds to.</description>
        <inlineHelpText>The Type of article that this record corresponds to.</inlineHelpText>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workaround</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ICT Article</label>
    <nameField>
        <displayFormat>Ar{0000000}</displayFormat>
        <label>ICT Article No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICT Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/objects/SLA__c.object
<CustomObject>
    <description>A record of the available SLAs that can be applied to Goals and Tickets</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the SLA currently active</description>
        <inlineHelpText>Is the SLA currently active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Acknowledgement_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If the SLA requires a customer acknowledgement within a certain number of days after commencement this should be specified here (0 for no acknowledgement required)</description>
        <inlineHelpText>If the SLA requires a customer acknowledgement within a certain number of days after commencement this should be specified here (0 for no acknowledgement required)</inlineHelpText>
        <label>Customer Acknowledgement (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Escalation_Prior_to_SLA_Breach_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If the record should be escalated a set number of days prior to SLA breach (assuming it hasn&apos;t already been escalated or closed) then specify the number of days before the SLA breach that the record should be escalated here. (0 = no auto escalation required)</description>
        <inlineHelpText>The number of days before the SLA breach that the record should be escalated here. (0 = escalation required)</inlineHelpText>
        <label>Escalation Prior to SLA Breach (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Length_Days__c</fullName>
        <description>The length of the SLA in days</description>
        <label>SLA Length (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working_Days__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked if the SLA is measured in working days, unchecked if it is measured in calendar days.</description>
        <inlineHelpText>Checked if the SLA is measured in working days, unchecked if it is measured in calendar days.</inlineHelpText>
        <label>Working Days</label>
        <type>Checkbox</type>
    </fields>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/TestDataCreator.cls
/*------------------------------------------------------------
Author:        Ana Lomibao
Company:       Arcus Global Ltd
Date:          October 2013
Description:   Class to create test data for unit tests
Test class:    InboundTicketEmailHandler_Test.cls
------------------------------------------------------------*/
public with sharing class TestDataCreator 
{
	public static Contact createContact(Id userId)
	{
		Contact c= new Contact(
			FirstName= 'Test',
			LastName= 'Test',
			Email= 'test.test@email.com', 
			MobilePhone= '0987083702',
			Title= 'Test', 
			User__c= userId);
		insert c;
		return c;	
	}
	
	public static User createUser()
	{
		UserRole ur= [Select Id From UserRole Where Name= 'System Administrator'];
		Profile up= [Select Id From Profile Where Name= 'System Administrator'];
		User u= new User(
			LastName= 'Test', 
			Alias= 'test',
			Email= 'test.test@email.com',
			UserRoleId= ur.Id,
			ProfileId= up.Id,
			Username= 'test.test@email.com',
			CommunityNickname= 'test',
			TimeZoneSidKey= 'Europe/London',
			LocaleSidKey= 'en_GB',
			EmailEncodingKey= 'ISO-8859-1',
			LanguageLocaleKey= 'en_US'
			);
				
		insert u;
		return u;
	}
	
	public static Id createCase()
	{
		RecordType rt= [Select Id From RecordType Where SobjectType= 'Case' And Name= 'CCC'];
		Case c= new Case(
			Status= 'Open', 
			Subject= 'Test Subject',
			Popular_Goals__c= 'test'
			);
		insert c;
		return c.Id; 
	}
	
	public static Id createTicket(String recTypeName, Id caseId)
	{
		RecordType rt= [Select Id From RecordType Where SobjectType= 'Ticket__c' And Name= :recTypeName];
		
		Ticket__c t= new Ticket__c(
			RecordTypeId= rt.Id,
			GLOBAL_Goal__c= caseId, 
			GLOBAL_Ticket_Status__c= 'Draft'
			);
		insert t;
		return t.Id;
	}
	
	public static SLA__c createSLA()
	{
		SLA__c sla= new SLA__c(
			Active__c= true, 
			Escalation_Prior_to_SLA_Breach_Days__c= 3, 
			Customer_Acknowledgement_Days__c= 2, 
			Working_Days__c= true, 
			SLA_Length_Days__c= 7, 
			Name= '7 Working Days'
			);
		insert sla;
		return sla;
	}
	
	public static ICT_Article__c createIctArticle(String artName)
	{
		ICT_Article__c art= new ICT_Article__c
			(
			Article_Name__c= artName,
			Article_Type__c= 'Fix'
			);
		insert art;
		return art;
	}
	
}