SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Goal_Free_Text__c</fullName>
        <description>A free text description of the case if none of the the drop down types are applicable</description>
        <inlineHelpText>Describe customer&apos;s aim (if not found in Top Enquiries or selected Other Sub type)</inlineHelpText>
        <label>Case Subject</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>CCC</fullName>
        <active>true</active>
        <businessProcess>Goal Process</businessProcess>
        <description>A case as used by the Customer Contact Centre</description>
        <label>CCC</label>
    </recordTypes>
</CustomObject>

SourceMetaData/src/objects/Related_Ticket__c.object
<CustomObject>
    <description>A lookup table to enable many-to-many ticket inter-relationships.</description>
    <fields>
        <fullName>Ticket_From__c</fullName>
        <description>The ticket that the relationship is from (related list not used on page layouts)</description>
        <inlineHelpText>The ticket that the relationship is from (related list not used on page layouts)</inlineHelpText>
        <label>Ticket From</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipLabel>Related Tickets (From)</relationshipLabel>
        <relationshipName>Tickets_From</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ticket_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The ticket that the relationship is to (related list used on page layouts)</description>
        <inlineHelpText>The ticket that the relationship is to (related list used on page layouts)</inlineHelpText>
        <label>Ticket To</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipLabel>Related Tickets</relationshipLabel>
        <relationshipName>Tickets_To</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Related Ticket</label>
    <nameField>
        <displayFormat>RelTckt{000000}</displayFormat>
        <label>Related Tickets Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Service__c</fullName>
        <description>The specific service that is responsible for this ticket. (This field is used on the generic ticket record type but will be superseded when service specific record types are created)</description>
        <inlineHelpText>The specific service that is responsible for this ticket.</inlineHelpText>
        <label>Service</label>
        <picklist>
            <controllingField>GLOBAL_Service_Group__c</controllingField>
            <picklistValues>
                <fullName>Adult and community education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaint - Adult Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaint - Childrens Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Compliment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Compliment - Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Concern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Concern - Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Enquiry  - Adult Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Request for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Agresso Actions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Queries and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - ICT Ticket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Payroll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Democratic and electoral services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HHW_Enquiry_Description__c</fullName>
        <description>More details about the problem (optional)</description>
        <inlineHelpText>More details about the problem (optional)</inlineHelpText>
        <label>Enquiry Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Hounslow_Borough__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If enquiry is not about a specific location, or you cannot find street name, please check the box &apos;Hounslow Borough&apos;. Otherwise leave unchecked and specify Location in Target.</description>
        <inlineHelpText>If enquiry is not about a specific location, or you cannot find street name, please check the box &apos;Hounslow Borough&apos;. Otherwise leave unchecked and specify Location in Target.</inlineHelpText>
        <label>Hounslow Borough</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HHW_Location_Details__c</fullName>
        <description>Free-text location details used in Highways enquiries</description>
        <inlineHelpText>If enquiry is not about a specific location, or you cannot find the street name, please select &apos;Hounslow Borough&apos;. Enter more details about the location.</inlineHelpText>
        <label>Location Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HHW_Location__c</fullName>
        <description>Address selected via Target</description>
        <inlineHelpText>Please select street via Target or, if location is not found, tick &quot;Hounslow Borough&quot; checkbox</inlineHelpText>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Service__c</fullName>
        <description>Highways Service Area</description>
        <inlineHelpText>Highways Service Area</inlineHelpText>
        <label>Highways Service</label>
        <picklist>
            <picklistValues>
                <fullName>Drainage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Kerb Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ironwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licence Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Lights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Signs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traffic Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trees, Shrubs &amp; Vegetation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HHW_Subcategory__c</fullName>
        <description>A list of standard enquiries of Hounslow Homes</description>
        <inlineHelpText>Select a matching topic or General Enquiry</inlineHelpText>
        <label>Highways Sub-category</label>
        <picklist>
            <controllingField>HHW_Service__c</controllingField>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Smell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Drop Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freedom Of Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged/ Cracked Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Licence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Opportunities &amp; Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage To Pedestrian Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fault On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstruction On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Ice, Snow And Frost On Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Pothole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction (unauthorised)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spillage On Network (spillage On Road/footway/footpath)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streetlight/bollard Knocked Down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Dropped Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Shop Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Skip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uneven Footway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Animal On A Road Or Footpath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dog Fouling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <recordTypes>
        <fullName>Highways</fullName>
        <active>true</active>
        <description>Hounslow Highways (Field Prefix = HHW)</description>
        <label>Highways</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/TestClass.cls
/*------------------------------------------------------------
Author:        Matt Urbanowski
Company:       Arcus Global Ltd
Date:          24/06/2013
Description:   Class containing all test classes for extensions / classes / triggers etc.
               Also contains private functions for creating test records
Test Class:    TestClass
------------------------------------------------------------*/
@isTest
public class TestClass {

    public static Account CreateTestPerson() {
        RecordType PersonrecordType = [select Id, Name, DeveloperName from RecordType where SObjectType = 'Account' and IsPersonType = true limit 1 ];
        Account testPerson = New Account(FirstName='Bob', LastName='Test', RecordTypeId=PersonrecordType.Id, Phone='000000');
        insert testPerson;
        return testPerson;       
    }
    
    public static Account CreateTestAccount() {
        Account a = new Account(Name='Test Account');
        insert a;
        return a;
    }
    
    public static Contact CreateTestContact(Account testAccount) {
        Contact c = new Contact(FirstName='Susan', LastName='Cook', Phone='000', Email='t@t.t', AccountId=testAccount.id, MobilePhone= '0987083702');
        insert c;
        return c;
    }
    
    public static User CreateTestUser() {
        Profile adminProfile = [Select Id From Profile Where Name = 'System Administrator'];
        return [Select Id, Name from User Where UserType = 'Standard' and isActive = true and ProfileId = :adminProfile.Id Limit 1][0];
    }
    
    public static Case CreateTestCase(Contact testContact) {
        Case testCase = new Case(Subject='Test', ContactId = testContact.Id,Goal_Free_Text__c = 'Test',  OwnerId = CreateTestUser().Id);
        insert testCase;
        return testCase;
    }
    
    public static Ticket__c CreateTestTicket(Case testCase) {
        Ticket__c testTicket = new Ticket__c(GLOBAL_Service__c='Test', GLOBAL_Goal__c=testCase.Id, OwnerId = CreateTestUser().Id);
        insert testTicket;
        return testTicket;        
    }
    
    public static Ticket__c CreateTestHighwaysTicket(Case testCase) {
        Ticket__c testTicket = new Ticket__c(GLOBAL_Service__c='Test', GLOBAL_Goal__c=testCase.Id, OwnerId = CreateTestUser().Id);
               //configure ticket with Highways Data             
        testTicket.HHW_Hounslow_Borough__c = TRUE;
        testTicket.HHW_Service__c = 'Drainage';
        testTicket.HHW_Subcategory__c = 'Bad Smell';
        testTicket.HHW_Location_Details__c = '';
        testTicket.HHW_Location__c = '';
        testTicket.HHW_Enquiry_Description__c = ''; 
        insert testTicket;
        return testTicket;        
    }
    
    public static Attachment CreateTestAttachment(id parentId, String attachmentName, String bodyName) {
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        Attachment testAttachment = new Attachment(ParentId = parentId, Name = 'test attachment', Body = bodyBlob );
        insert testAttachment;
        return testAttachment;        
    }
    
    public static Attachment CreateTestAttachment(id parentId) {
        return CreateTestAttachment(parentId, 'test attachment', 'Unit Test Attachment Body' );
    }
    
    public static Task CreateTestTask(id parentId) {
        Task testTask = new Task(WhatId = parentId, Subject = 'test attachment' , status = 'Completed');
        insert testTask;
        return testTask;        
    }
    
    // Test method for Creating Related Tickets
    static TestMethod void testRelated_Ticket() 
    {
        Test.startTest();
        Case testCase1 = CreateTestCase(CreateTestContact(CreateTestAccount()));
        Case testCase2 = CreateTestCase(CreateTestContact(CreateTestAccount()));
        Related_Ticket__c RT = new Related_Ticket__c(Ticket_From__c=CreateTestTicket(testCase1).Id,
                                                     Ticket_To__c=CreateTestTicket(testCase2).Id);
        insert RT; 
        Test.stopTest();    
    }


    // Test method for CreateTicket extension class
    static TestMethod void testExtCreateTicket()
    {
        Test.startTest();
        Case testCase = CreateTestCase(CreateTestContact(CreateTestAccount()));
        PageReference pg = new PageReference(Page.CreateTicket+ '?id=' + testCase.Id);
        Test.setCurrentPage(pg);
        ExtCreateTicket myExt = new ExtCreateTicket(new ApexPages.StandardController(testCase));
        myExt.TicketPlaceholder.GLOBAL_Service__c = 'CCC - Payroll';
        myExt.CreateTicket();
        // Test payment flow
        myExt.TicketPlaceholder.GLOBAL_Service__c = 'Payment';
        myExt.CreateTicket();
        myExt.Cancel();
        Test.stopTest();  
    }

}