SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>REP_Customer_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</description>
        <inlineHelpText>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Goals</relationshipLabel>
        <relationshipName>Representing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SLA requirement</description>
        <inlineHelpText>SLA requirement</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CSC</fullName>
        <active>true</active>
        <businessProcess>Goal Process</businessProcess>
        <description>A case as used by the Corporate Services Centre</description>
        <label>CSC</label>
    </recordTypes>
</CustomObject>

SourceMetaData/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user account that the contact is associated with</description>
        <inlineHelpText>The user account that the contact is associated with</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/SLA__c.object
<CustomObject>
    <description>A record of the available SLAs that can be applied to Goals and Tickets</description>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 2 - Chidlren&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Children&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Adult&apos;s Social Care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Closed_Date__c</fullName>
        <inlineHelpText>Ticket was closed on this date (blank for not-closed ticket)</inlineHelpText>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer who has reported the case that this record is a child of</description>
        <inlineHelpText>The customer who has reported the case that this record is a child of</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Feedback_Cutoff_Date__c</fullName>
        <description>The latest date at which the customer cna provide feedback or request that a closed ticket is re-opened</description>
        <inlineHelpText>The latest date at which the customer cna provide feedback or request that a closed ticket is re-opened (3 working days after closed date)</inlineHelpText>
        <label>Feedback Cutoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer&apos;s representative (set on the case record)</description>
        <inlineHelpText>The customer&apos;s representative (set on the case record)</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Tickets</relationshipLabel>
        <relationshipName>Tickets_Acting_as_Representative_on</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ticket SLA requirements.</description>
        <inlineHelpText>Ticket SLA requirements.</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/InboundTicketEmailHandler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest(seeAllData= false)
private class InboundTicketEmailHandler_Test 
{
	
    static testMethod void handleInboundEmailTest() 
    {
    	User uRA= [Select Id From User Where Name= 'Root Administrator'];
    	System.runAs(uRA)
    	{
    		Test.startTest();
	    	/** 
	    	 * Create test data
	    	 **/ 
	    	// create contact with user 
	       	User u= TestDataCreator.createUser();
	       	system.assertNotEquals(u, null);
	       	Contact con= TestDataCreator.createContact(u.Id);
	       	
	   	 	// create case
			Id caseId= TestDataCreator.createCase();    	 
	       	Case ictCase= [Select Id, ContactId From Case Where Id= :caseId];
	       	ictCase.ContactId= con.Id;
	       	ictCase.REP_Customer_Representative__c= con.Id;
	       	update ictCase;
	       	
	    	// create an ICT ticket on the case
	        Id tId= TestDataCreator.createTicket('CSC - ICT Ticket', ictCase.Id);
	        Ticket__c ticket= [Select Id, Name, RecordTypeId, GLOBAL_Ticket_Status__c, GLOBAL_Goal__c, GLOBAL_Customer__c, GLOBAL_Representative__c, GLOBAL_Feedback_Cutoff_Date__c 
	        	From Ticket__c Where Id= :tId];
	       	// assert that the customer has propagated from the case to the ticket
	       	System.assertEquals(ticket.GLOBAL_Customer__c, con.Id);
	       	
	       	// assert that ticket.GLOBAL_Customer__c is a contact associated to a user
			Map<Id,Contact> contactUsers= new Map<Id,Contact>();
			contactUsers.putAll([Select Id, User__c, User__r.Email From Contact Where Id= :ticket.GLOBAL_Customer__c]);
			System.assertNotEquals(contactUsers.get(ticket.GLOBAL_Customer__c), null);
	       	
	       	// open the ticket, this will:
	       	// - send an email to the customer
	       	// - log the event with a task
	       	ticket.GLOBAL_Ticket_Status__c= EmailUserOnOpenedTicket.TICKET_OPEN_STATUS;
	       	ContextHelper.TICKET_TRIGGER_FIRST_CALL= true;
	       	update ticket;
	       	
	       	// a task has been created
	       	List<Task> tasks;
	       	tasks= [Select Id, RecordTypeId, RecordType.Name, Subject From Task Where WhatId= :ticket.Id Order by Createddate Desc];
	       	System.assertNotEquals(0, tasks.size());
	       	System.assertEquals(tasks[0].Subject, EmailUserOnOpenedTicket.TASK_SUBJECT);
	       	delete tasks;
	       	
	        // create email and envelop objects, with subject containing a valid Ticket Name
	        Messaging.Inboundemail em= new Messaging.Inboundemail();
	        Messaging.Inboundenvelope env= new Messaging.Inboundenvelope();
	       	em.plainTextBody= 'Test body.';
	       	em.subject= 'test this ticket number ' + ticket.Name;
	       	em.fromAddress= 'test@test.com';
	       	
	       	// create email class handler to test when an email is received
	       	InboundTicketEmailHandler emHandler= new InboundTicketEmailHandler();
	       	Messaging.Inboundemailresult res= emHandler.handleInboundEmail(em, env);
	       	
	       	// the received email will be logged as a task in the system
	       	tasks= [Select Id, subject, RecordTypeId, RecordType.Name From Task Where WhatId= :ticket.Id Order by Createddate Desc];
	       	system.assertNotEquals(null, tasks);
	       	system.assertEquals(tasks[0].RecordType.Name, CreateTaskICTFeedback.RECORD_TYPE_NAME);
	       	system.assertEquals(tasks[0].subject, CreateTaskICTFeedback.EMAIL_ON_TIME_SUBJECT);
	       	delete tasks;
	       	
	        // close the ticket, this will
	        // - send email to the customer 
	        // - log the event with a task	        
			SLA__c sla= TestDataCreator.createSLA();
	        ticket.GLOBAL_Active_SLA__c= sla.Name; 	        
	        ticket.GLOBAL_Ticket_Status__c= 'Closed';
	        ticket.GLOBAL_Closed_Date__c= Date.today();
	        ContextHelper.TICKET_TRIGGER_FIRST_CALL= true;
	        update ticket;
	        ticket= [Select Id, GLOBAL_Ticket_Status__c, Name, GLOBAL_Feedback_Cutoff_Date__c, GLOBAL_Active_SLA__c, GLOBAL_SLA__c From Ticket__c Where Id= :tId];
			System.assertNotEquals(ticket.GLOBAL_Feedback_Cutoff_Date__c, null);
			tasks= [Select Id, subject, RecordTypeId, RecordType.Name From Task Where WhatId= :ticket.Id Order by Createddate Desc];
			system.assertNotEquals(tasks.size(), 0);
			system.assertEquals(tasks[0].Subject, EmailUserOnClosedTicket.TASK_SUBJECT);
			Test.stopTest();
    	}
    }
    

}