SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Goal_Free_Text__c</fullName>
        <description>A free text description of the case if none of the the drop down types are applicable</description>
        <inlineHelpText>Describe customer&apos;s aim (if not found in Top Enquiries or selected Other Sub type)</inlineHelpText>
        <label>Case Subject</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>CSC</fullName>
        <active>true</active>
        <businessProcess>Goal Process</businessProcess>
        <description>A case as used by the Corporate Services Centre</description>
        <label>CSC</label>
    </recordTypes>
</CustomObject>

SourceMetaData/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user account that the contact is associated with</description>
        <inlineHelpText>The user account that the contact is associated with</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>FOI_Type__c</fullName>
        <inlineHelpText>Type of Information request:
Freedom of Information Request
Environmental Information Request
Service Access Request
Data Protection Act</inlineHelpText>
        <label>RFI Type</label>
        <picklist>
            <picklistValues>
                <fullName>FOI</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>EIR</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>SAR</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DPA</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 2 - Chidlren&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Children&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Adult&apos;s Social Care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer_Id__c</fullName>
        <description>For use when identifying customer ID from a ticket.</description>
        <formula>GLOBAL_Goal__r.Contact.Id</formula>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer_Name__c</fullName>
        <formula>GLOBAL_Goal__r.Contact.Salutation_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal_Summary__c</fullName>
        <formula>GLOBAL_Goal__r.Subject</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Subject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_IsReopenTicket__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ticket was Reopened via pressing a button. Field is used in a workflow rule and doesn&apos;t need to be on the layout</description>
        <inlineHelpText>Ticket was Reopened</inlineHelpText>
        <label>Reopened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Received_Date__c</fullName>
        <description>Date when communication was received</description>
        <inlineHelpText>Date when communication was received</inlineHelpText>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/ActionSubmitFinanceTicketController.cls
public class ActionSubmitFinanceTicketController {
/*
    
    public Ticket__c myTicket { get; set; }
    public Case myCase { get; set; }
    public List<RecordType> ticketRecordTypes { get; set; }
    public List<SelectOption> RecordTypeList { get; set; }
    public List<Schema.FieldSetMember> finaceTicketFields { get; set; }
    public Boolean showForm { get; set; }
    public Boolean showResults { get; set; }
    public Id selectedTicketRecordType { get; set; }
    public Attachment attachment {
        get {
            if (attachment == null)
                attachment = new Attachment();
            return attachment;
        }
        set;
    }

    
    public ActionSubmitFinanceTicketController () {
        // Constructor 
        // Create a case adn ticket object. Set case to some standard values.
        
        // Get the finance ticket record types and add them to a list for selection
        showForm = true;
        showResults = false;
        ticketRecordTypes =  [SELECT Id,SobjectType,Name FROM RecordType WHERE SobjectType ='Ticket__c' AND Name LIKE '%Finan%'  ];
        RecordTypeList = new List<SelectOption>();
        System.debug(ticketRecordTypes );
        for (RecordType rt: ticketRecordTypes )
        {
            RecordTypeList.add(new SelectOption(rt.Id, rt.Name) );
        }
        
        // Create Ticket and Case object, set intial values
        myCase = new Case(Goal_Free_Text__c = 'Test'  );
        // For the case fields that should be set
        //DONE
        // Owner - Finance Queue
        // Origin - Chatter
        // Record Type - CSC
        // Customer - Assume that the current user has a linked contact record. Use SOQL to get this record.
        // TO DO
        // Service Area
        myCase.RecordTypeId = [SELECT Id,SobjectType,Name FROM RecordType WHERE Name ='CSC' AND SobjectType ='Case'  LIMIT 1].Id;
        myCase.OwnerId = [SELECT Id,Type,Name FROM Group WHERE Name = 'CSC - Finance Operations' AND Type ='Queue'  LIMIT 1].Id;
        myCase.ContactId = [SELECT Id,Name,User__c FROM Contact WHERE User__c =: UserInfo.getUserId()  LIMIT 1].Id;
        myCase.Origin = 'Chatter';
        
        // Create the ticket, inherit owner from case
        myTicket = new Ticket__c( OwnerId = myCase.OwnerId  );
        
        // Get the ticket fields that we need to set for a finace ticket (as in the finace field set)
        finaceTicketFields = new List<Schema.FieldSetMember>();
        finaceTicketFields =  SObjectType.Ticket__c.FieldSets.Finance_Request_Field_Set.getFields();
        
        System.debug('myTicket = ' + myTicket  );
        System.debug('myCase = ' + myCase );
        System.debug('finaceTicketFields = ' + finaceTicketFields );
    }
    
    public PageReference Submit(){
        System.debug('submit '  );
        System.debug('submit ' + RecordTypeList  );
        
        //1 - Insert Cast, Ticket and Attachment into the DML
        
        System.debug('myCase = ' + myCase );
        
        insert(myCase);
        
        myTicket.GLOBAL_Goal__c=myCase.Id;
        //myTicket.RecordTypeId = 
        System.debug('myTicket = ' + myTicket  );
        insert(myTicket );
        System.debug('AFTER INSERT myTicket = ' + myTicket  );
        
        // Now upload the attachment
        attachment.OwnerId = UserInfo.getUserId();
        attachment.ParentId = myTicket.Id; 
        attachment.IsPrivate = false;
        
        try {
            insert attachment;
        } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading attachment'));
            return null;
        } finally {
            attachment = new Attachment(); 
        }
        
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Attachment uploaded successfully'));

        
        //myTicket = new Ticket__c( [SELECT Id, IsDeleted, Name, CreatedDate, RecordTypeId, LastModifiedById, GLOBAL_Active_SLA__c, GLOBAL_Received_Date__c, 
        //GLOBAL_Customer_Id__c, GLOBAL_Goal_Summary__c, GLOBAL_Customer_Name__c, GLOBAL_IsReopenTicket__c, FOI_Type__c, GLOBAL_Goal__c FROM Ticket__c
        //WHERE Id =:myTicket.Id LIMIT 1 ]  );
        
        showForm = false;
        showResults = true;
        
        // here after insert we also want to create chatter posts logging the creation and adding into users feed.
        
        //Chatter Actions
        	//1 - Report to follow ticket that has been created
        	//2 - post into the users feed
        
        //1
        EntitySubscription follow = new EntitySubscription (parentId = myTicket.Id, subscriberid = UserInfo.getUserId()); //your User Id
		insert follow;

        //2 - insert a post in users chatter feed
        FeedItem post = new FeedItem();
        post.ParentId = UserInfo.getUserId(); //eg. Opportunity id, custom object id..
        post.Body = 'Finance Request Submitted';
        insert post;   
        return null ;
    }
*/
}