SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Popular_Goals__c</fullName>
        <description>A list of popular goals that customers have</description>
        <inlineHelpText>The most frequent customers enquiries</inlineHelpText>
        <label>Top Enquiries</label>
        <picklist>
            <picklistValues>
                <fullName>Animal Warden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Badge/Freedom Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pest Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pollution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tidy Town</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waste Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other &gt;</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Service_Group__c</fullName>
        <description>The service group for the ticket.</description>
        <inlineHelpText>The service group for the ticket.</inlineHelpText>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Service Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Contact Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regeneration, Economic Development and Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enquiry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Service__c</fullName>
        <description>The specific service that is responsible for this ticket. (This field is used on the generic ticket record type but will be superseded when service specific record types are created)</description>
        <inlineHelpText>The specific service that is responsible for this ticket.</inlineHelpText>
        <label>Service</label>
        <picklist>
            <controllingField>GLOBAL_Service_Group__c</controllingField>
            <picklistValues>
                <fullName>Adult and community education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaint - Adult Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaint - Childrens Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Compliment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Compliment - Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Concern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Concern - Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Enquiry  - Adult Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Request for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Agresso Actions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Queries and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - ICT Ticket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Payroll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Democratic and electoral services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <recordTypes>
        <fullName>Highways</fullName>
        <active>true</active>
        <description>Hounslow Highways (Field Prefix = HHW)</description>
        <label>Highways</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/ConfirmTicketControllerExtension_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ConfirmTicketControllerExtension_Test 
{

    static testMethod void testConfirmTicketSubmit() 
    {
    	// Set the current page
        Pagereference pageRef= Page.TicketConfirmSubmit;
        Test.setCurrentPage(pageRef);
        //Apexpages.Standardcontroller scon= new Apexpages.Standardcontroller();
        // Create extension controller
        //ConfirmTicketControllerExtension cont= new ConfirmTicketControllerExtension();
        
        Map<String, String> params= pageRef.getParameters();
        
        // create test data
        Case c= new Case(
        	Subject= 'Test Subject',
        	Status= 'Open',
        	Popular_Goals__c= 'Highways'
        	);
        insert c;
        
        Ticket__c t= new Ticket__c(
        	GLOBAL_Goal__c= c.Id,
        	GLOBAL_Service_Group__c= 'Chief Executive',
        	GLOBAL_Service__c= 'Human Resources'
        	);
        insert t;
        	
        // add parameters to the VF page	
        params.put('Id', t.Id);
        
        // set the current page to execute the extension class
        Test.setCurrentPage(pageRef);
        
        
        
    }
}