SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SLA requirement</description>
        <inlineHelpText>SLA requirement</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/SLA__c.object
<CustomObject>
    <description>A record of the available SLAs that can be applied to Goals and Tickets</description>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Service_Group__c</fullName>
        <description>The service group for the ticket.</description>
        <inlineHelpText>The service group for the ticket.</inlineHelpText>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Service Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Contact Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regeneration, Economic Development and Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enquiry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Service__c</fullName>
        <description>The specific service that is responsible for this ticket. (This field is used on the generic ticket record type but will be superseded when service specific record types are created)</description>
        <inlineHelpText>The specific service that is responsible for this ticket.</inlineHelpText>
        <label>Service</label>
        <picklist>
            <controllingField>GLOBAL_Service_Group__c</controllingField>
            <picklistValues>
                <fullName>Adult and community education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaint - Adult Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaint - Childrens Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Complaints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Compliment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Compliment - Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Concern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Concern - Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Enquiry  - Adult Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC - Request for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s social care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Agresso Actions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Finance - Queries and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - ICT Ticket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Payroll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC - Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Democratic and electoral services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/ExtCreateTicket.cls
/*------------------------------------------------------------
Author:        Matt Urbanowski
Company:       Arcus Global Ltd
Date:          21/07/2013
Description:   Extension class for Create Ticket VF Page. Creates a new ticket with 
               record type based on selected service group / service
               Also does a smart search on match for the closest service type.
Test Class:    TestClass
------------------------------------------------------------*/

public with sharing class ExtCreateTicket {

    public Id selRTItem {get; set;}
    public Id selDeptItem {get; set;}
    public Ticket__c TicketPlaceholder {get; set;}
    public String txtError {get; set;}
    public Case myCase {get; set;} 
    public Id PaymentRTId {get; set;}
    public PageReference ReturnToGoalPR {get; set;}
    public Boolean showTicketType {get; set;}
    public Boolean showPayment {get; set;}
    public Boolean ticketsInheritGoalSLA  {get; set;}
    //public Flow.Interview.PAY_Payment_Ticket myInterview {get; set;}

    private String txtInstance;
    private String TicketObjId = 'a06';
    
    // Field ID Values
    private String Param1Id = '00Nb0000002zVyf'; // Status
    private String Param2Id = '00Nb0000003dfYj'; // Service Group
    private String Param3Id = '00Nb0000003dfYk'; // Service
    private String Param4Id = 'CF00Nb0000002zMJP'; // Parent Goal
    private String Param5Id = 'CF00Nb0000003ejYf'; // SLA
    private String Param6Id = '00Nb0000003f9VO'; // SLA picklist
    
    private String DefaultStatusValue = 'Draft';
      
    public ExtCreateTicket(ApexPages.StandardController controller) {
        // Startup function. Defaults
        this.myCase = (Case)Controller.getRecord();
        myCase = [Select CaseNumber, SLA__r.Name, Subject, Active_SLA__c from Case Where Id=:ApexPages.currentPage().getParameters().get('id')][0];
        TicketPlaceholder = New Ticket__c(GLOBAL_Goal__c = ApexPages.currentPage().getParameters().get('id'));
        ReturnToGoalPR = New ApexPages.StandardController(myCase).view();
        showTicketType = true;
        // DG - disabled tickets inheriting golas SLA as per customer request
        ticketsInheritGoalSLA = false;
        txtInstance = URL.getSalesforceBaseUrl().toExternalForm();
        
        // Default Service 
        String DefaultService = findDefaultService(myCase.Subject);
        if (DefaultService != null)
            TicketPlaceholder.GLOBAL_Service__c = DefaultService;
        
        // Default Service Group
        String DefaultServiceGroup = findDefaultServiceGroup(myCase.Subject);
        if (DefaultServiceGroup != null)
            TicketPlaceholder.GLOBAL_Service_Group__c = DefaultServiceGroup;
        
        
        
    }  
      
    private List<selectOption> getListTicketRecordTypes() {
        // Get list of all record type options
        List<selectOption> options = new List<selectOption>();
        List<RecordType> RecordTypes = [select Id, Name from RecordType where SobjectType = 'Ticket__c' Order By Name];
        for (RecordType rt : RecordTypes) {
            options.add(new selectOption(rt.Id, rt.Name));
            if (rt.Name.contains('Payment')) // Store record type Id of payment RT for later use
                PaymentRTId = rt.Id;
        }
        return options ;
    }
    
    public void CreatePayment() {
        // Show the correct panels
        showPayment = true;
        showTicketType = false;
    }
    
    public PageReference CreateTicket() {
        // Create a new ticket, then open it for editing
        String ParamRT = '';
        PageReference myPage;
        List<selectOption> TicketRecordTypes = getListTicketRecordTypes();
        
        if (TicketPlaceholder.GLOBAL_Service__c==null) { // Must specify a service
            txtError = 'You must select a service in order to create a ticket.';
            Return null;
        }
        else if (TicketPlaceholder.GLOBAL_Service__c.contains('Payment')) // If service selected has the word payment in it, load visual workflow
        {
            txtError = '';
            CreatePayment();
            Return null;
        } else {
            txtError = '';
            // Get the record type - based on service label
            for (selectOption eachOption : TicketRecordTypes)
                if (eachOption.getLabel() == TicketPlaceholder.GLOBAL_Service__c) {
                    ParamRT = '&RecordType=' + eachOption.getValue();        
                    break;
                }   
            String Param1 = '?' + Param1Id + '=' + DefaultStatusValue; // Status
            String Param2 = '&' + Param2Id + '=' + TicketPlaceholder.GLOBAL_Service_Group__c; // Service Group
            String Param3 = '&' + Param3Id + '=' + TicketPlaceholder.GLOBAL_Service__c; // Service
            String Param4 = '&' + Param4Id + '=' + myCase.CaseNumber; // Parent Goal
            
            
            // Set the SLA params (but only if tickets are inheriting case SLAs
            String Param5 = '';
            String Param6 = '';
            if (myCase.SLA__r.Name != null && ticketsInheritGoalSLA)
            {
                Param5 = '&' + Param5Id + '=' + myCase.SLA__r.Name; // SLA
            	Param6 = '&' + Param6Id + '=' + myCase.Active_SLA__c; // SLA Picklist
            }
            myPage = new PageReference(txtInstance + '/' + TicketObjId + '/e' + Param1 + Param2 + Param3 + Param4 + Param5 + Param6 + ParamRT);
            Return myPage;
        }
    }
    
    // Takes a subject and finds the most relevant service which matches it to default it.
    private String findDefaultService(String Subject) {
        try {
            Schema.DescribeFieldResult fieldResult = Ticket__c.GLOBAL_Service__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            // Smart search for ticket type
            String[] SubjectSplit = Subject.split(' ',-2);
            Map<String,Integer> resultCount = new Map<String,Integer>();
            
            for (String eachWord : SubjectSplit) {
                for (Schema.PicklistEntry f : ple)
                {
                    String eachWordStripped = eachWord.replace('-','').replace(' ','').replace('.','');
                    if (f.getLabel().containsIgnoreCase(eachWordStripped) && eachWordStripped != '') {
                        if (!resultCount.containsKey(f.getLabel())) {
                            resultCount.put(f.getLabel(),eachWordStripped.length());
                        } else {
                            resultCount.put(f.getLabel(),resultCount.get(f.getLabel())+eachWordStripped.length());
                        }
                    }
                }
            }
            // Loop through map and return result with most matches
            Integer maxResults = 0;
            String Result = null;
            
            for(String myValue: resultCount.keyset()) {
                System.debug('%%% ' + myValue + ' = ' + resultCount.get(myValue));
                if (resultCount.get(myValue) > maxResults) {
                    maxResults = resultCount.get(myValue);
                    Result = myValue;
                }
            }
            Return Result;
        } catch (Exception e) {
            System.debug(e);
            Return '';
        }
    }
    
    
    // Takes a subject and finds the most relevant service group which matches it to default it.
    private String findDefaultServiceGroup(String Subject) {
        try {
            if (Subject.toLowerCase().contains( 'complaint') )
                return 'Complaint';
            else if (Subject.toLowerCase().contains( 'complement'))
                return 'Complement';
            else if (Subject.toLowerCase().contains( 'concern'))
                return 'Concern';
            else
                return null;
        }
        catch (Exception e){
            System.debug(e);
            return null;
        }
    }
                
                
            	

    public PageReference Cancel() {
        Return new ApexPages.StandardController(myCase).view();
    }    

}