SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>REP_Customer_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</description>
        <inlineHelpText>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Goals</relationshipLabel>
        <relationshipName>Representing</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CSC</fullName>
        <active>true</active>
        <businessProcess>Goal Process</businessProcess>
        <description>A case as used by the Corporate Services Centre</description>
        <label>CSC</label>
    </recordTypes>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer who has reported the case that this record is a child of</description>
        <inlineHelpText>The customer who has reported the case that this record is a child of</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Feedback_Cutoff_Date__c</fullName>
        <description>The latest date at which the customer cna provide feedback or request that a closed ticket is re-opened</description>
        <inlineHelpText>The latest date at which the customer cna provide feedback or request that a closed ticket is re-opened (3 working days after closed date)</inlineHelpText>
        <label>Feedback Cutoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer&apos;s representative (set on the case record)</description>
        <inlineHelpText>The customer&apos;s representative (set on the case record)</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Tickets</relationshipLabel>
        <relationshipName>Tickets_Acting_as_Representative_on</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/ManageMultipleTicketsController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ManageMultipleTicketsController_Test 
{

    static testMethod void ManageMultipleTicketsController_Test() 
    {
    	User uRA= [Select Id From User Where Name= 'Root Administrator'];
    	System.runAs(uRA)
    	{
    		Test.startTest();
	       	User u= TestDataCreator.createUser();
	       	system.assertNotEquals(u, null);
	       	Contact cont= TestDataCreator.createContact(u.Id);
	       	
	   	 	// create case
			Id caseId= TestDataCreator.createCase();    	 
	       	Case ictCase= [Select Id, ContactId From Case Where Id= :caseId];
	       	ictCase.ContactId= cont.Id;
	       	ictCase.REP_Customer_Representative__c= cont.Id;
	       	update ictCase;
	       	
	    	// create an ICT tickets on the case
	        Id tId1= TestDataCreator.createTicket('CSC - ICT Ticket', ictCase.Id);
	        Id tId2= TestDataCreator.createTicket('CSC - ICT Ticket', ictCase.Id);
	        Id tId3= TestDataCreator.createTicket('CSC - ICT Ticket', ictCase.Id);
	        
	        Ticket__c ticket1= [Select Id, Name, RecordTypeId, GLOBAL_Ticket_Status__c, GLOBAL_Goal__c, GLOBAL_Customer__c, GLOBAL_Representative__c, GLOBAL_Feedback_Cutoff_Date__c 
	        	From Ticket__c Where Id= :tId1];
	        	
	        Ticket__c ticket2= [Select Id, Name, RecordTypeId, GLOBAL_Ticket_Status__c, GLOBAL_Goal__c, GLOBAL_Customer__c, GLOBAL_Representative__c, GLOBAL_Feedback_Cutoff_Date__c 
	        	From Ticket__c Where Id= :tId2];

	        Ticket__c ticket3= [Select Id, Name, RecordTypeId, GLOBAL_Ticket_Status__c, GLOBAL_Goal__c, GLOBAL_Customer__c, GLOBAL_Representative__c, GLOBAL_Feedback_Cutoff_Date__c 
	        	From Ticket__c Where Id= :tId3];	        		        	
	        
	        Apexpages.Standardcontroller scon= new Apexpages.Standardcontroller(ticket1);
	        ManageMultipleTicketsController con= new ManageMultipleTicketsController(scon);
	        
	        List<ManageMultipleTicketsController.TicketWrapper> l = con.ticketList;

	        // link all tickets
	        for (ManageMultipleTicketsController.TicketWrapper tw: l)
	        {
	        	tw.addLink= true;
	        }
	        Pagereference pref= con.link();
	        
	        // unlink all tickets
	        for (ManageMultipleTicketsController.TicketWrapper tw: l)
	        {
	        	tw.addLink= false;
	        }
	        pref= con.unlink();	        
	        
	        Test.stopTest();
    	}    	
    }
}