SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>REP_Customer_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</description>
        <inlineHelpText>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Goals</relationshipLabel>
        <relationshipName>Representing</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer who has reported the case that this record is a child of</description>
        <inlineHelpText>The customer who has reported the case that this record is a child of</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer&apos;s representative (set on the case record)</description>
        <inlineHelpText>The customer&apos;s representative (set on the case record)</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Tickets</relationshipLabel>
        <relationshipName>Tickets_Acting_as_Representative_on</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/trigger_Ticket_Customer_Lookup.cls
/*------------------------------------------------------------
Author:        Douglas Guthrie
Company:       Arcus Global Ltd
Date:          31/07/2013
Description:   When a ticket is saved set the Customer and Representative
               Lookup fields equal to the goal lookups.     
Test Class:    TestClass
------------------------------------------------------------*/
public class trigger_Ticket_Customer_Lookup{

    
    
    public trigger_Ticket_Customer_Lookup(Ticket__c[] newTickets) 
    {
        // Get a list of the parent case customers and representatives for all tickets passed in
        System.debug('*****trigger_Ticket_Customer_Lookup');  
        
        List<Id> caseIds = new List<id>();
        for (Ticket__c myTicket : newTickets) 
        {
            caseIds.add(myTicket.GLOBAL_Goal__c);
        }
        Map<ID, Case> parentCases = new Map<ID, Case>([SELECT Id, ContactId, REP_Customer_Representative__c From Case Where Id IN : (caseIds)]);
        System.debug(parentCases);  
        
        // For each ticket in trigger set its lookup fields for customer and representatvie to mathc those of its parent case
        for (Ticket__c myTicket : newTickets) 
        {
        	if (parentCases.get(myTicket.GLOBAL_Goal__c) != null)
        	{    
	            myTicket.GLOBAL_Representative__c = parentCases.get(myTicket.GLOBAL_Goal__c).REP_Customer_Representative__c;
	            myTicket.GLOBAL_Customer__c = parentCases.get(myTicket.GLOBAL_Goal__c).ContactId ;
            
	            System.Debug ('***** Representative /  Customer: ');
	            System.Debug (parentCases.get(myTicket.GLOBAL_Goal__c));
	            System.Debug (myTicket.GLOBAL_Representative__c);
	            System.Debug (myTicket.GLOBAL_Customer__c);
        	}
        }

    }
}