SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Calendar_Days_Elapsed__c</fullName>
        <description>Number of calendar days when Goal was open or escalated</description>
        <inlineHelpText>Number of calendar days when Goal was open or escalated</inlineHelpText>
        <label>Calendar Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Expected_Breach_Date__c</fullName>
        <label>Case Expected Breach Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Expected_Escalation_Date__c</fullName>
        <label>Case Expected Escalation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opened_Date__c</fullName>
        <description>The date at which the case moved to the open state</description>
        <inlineHelpText>Goal status was changed to Open on this date</inlineHelpText>
        <label>Opened Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA_Days_Remaining__c</fullName>
        <description>The number of days remaining until SLA deadline. Measured in working or calendar days depending on the SLA</description>
        <formula>IF ( ISPICKVAL(Status, &quot;Draft&quot;), 
null, 

IF( SLA__r.Working_Days__c = TRUE, 
SLA__r.SLA_Length_Days__c - Working_Days_Elapsed__c, 
SLA__r.SLA_Length_Days__c - Calendar_Days_Elapsed__c) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The number of days remaining until SLA deadline. Measured in working or calendar days depending on the SLA.</inlineHelpText>
        <label>SLA Days Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SLA requirement</description>
        <inlineHelpText>SLA requirement</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Working_Days_Elapsed__c</fullName>
        <description>Number of working days when the Case was opened or escalated</description>
        <inlineHelpText>Number of working days when the Case was opened or eesclated</inlineHelpText>
        <label>Working Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/SLA__c.object
<CustomObject>
    <description>A record of the available SLAs that can be applied to Goals and Tickets</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>An optional description of the SLA (eg to describe what it is used for)</description>
        <inlineHelpText>An optional description of the SLA (eg to describe what it is used for)</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Prior_to_SLA_Breach_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If the record should be escalated a set number of days prior to SLA breach (assuming it hasn&apos;t already been escalated or closed) then specify the number of days before the SLA breach that the record should be escalated here. (0 = no auto escalation required)</description>
        <inlineHelpText>The number of days before the SLA breach that the record should be escalated here. (0 = escalation required)</inlineHelpText>
        <label>Escalation Prior to SLA Breach (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Length_Days__c</fullName>
        <description>The length of the SLA in days</description>
        <label>SLA Length (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working_Days__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked if the SLA is measured in working days, unchecked if it is measured in calendar days.</description>
        <inlineHelpText>Checked if the SLA is measured in working days, unchecked if it is measured in calendar days.</inlineHelpText>
        <label>Working Days</label>
        <type>Checkbox</type>
    </fields>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/trigger_Case_SLA.cls
/*------------------------------------------------------------
Author:        Matt Urbanowski
Company:       Arcus Global Ltd
Date:          26/07/2013
Description:   Takes the value in SLA picklist and assigns it the relevant lookup value from the SLA object.
Test Class:    SLATestClass
------------------------------------------------------------*/
public class trigger_Case_SLA {

    public trigger_Case_SLA(Case[] newCases) {
        // SOQL ------
        // Get list of all SLA lookups
        List<SLA__c> SLAs = [Select Id, Name, Description__c, Working_Days__c, Escalation_Prior_to_SLA_Breach_Days__c, SLA_Length_Days__c  from SLA__c];
        // Get list of upcoming Holidays, then add all holiday dates to a set of dates
        Set<Date> upcomingHolidayDates = UtilityDateMethods.GetUpcomingHolidayDates();
        // ---- End of SOQL
        
        Integer noOfDaysToBreach;
        Integer noOfDaysToEsc;

        for (Case myCase : newCases) {
            Integer MatchingSLAs = 0;
            if (myCase.Active_SLA__c == null) {  // Blank SLA
                myCase.Case_Expected_Breach_Date__c = null;
                myCase.Case_Expected_Escalation_Date__c = null;
                myCase.SLA__c = null;
                MatchingSLAs++;
            } else {
                for (SLA__c mySLA : SLAs) // Find relevant SLA from lookup table and apply
                    if (myCase.Active_SLA__c == mySLA.Name) {
                        MatchingSLAs++;
                        myCase.SLA__c = mySLA.Id;
                                                            
                        // Now that an SLA has been matched need to update the expected escalation data nad expected breach date fields on the object.
                        // Note that when calculating this it is NOT SAFE to use the myCase.SLA_Days_Remaining__c field as it is a formula field and will not have updated yet as a result of SLA change (before trigger preeceds it)
                        // Fields to use
                            //Case: Status,Opened_Date__c, Calendar_Days_Elapsed__c, Working_Days_Elapsed__c
                            //SLA: Working_Days__c, Escalation_Prior_to_SLA_Breach_Days__c,SLA_Length_Days__c
                        // Use these to calcualte the days of SLA that are left (and days left before escalation is required) and pass these to CalcEscOrBreachDate helper method. 
                        
                        noOfDaysToBreach = UtilityDateMethods.GetNoDaysTillBreach( mySLA, (Integer)myCase.Working_Days_Elapsed__c, (Integer)myCase.Calendar_Days_Elapsed__c);
                        noOfDaysToEsc = UtilityDateMethods.GetNoDaysTillEsc(mySLA, (Integer)myCase.Working_Days_Elapsed__c, (Integer)myCase.Calendar_Days_Elapsed__c);
                                                
                        // Pass params to the funtion to set expected esc and breach dates
                        myCase.Case_Expected_Breach_Date__c = UtilityDateMethods.forecastFutureEventDate(myCase.Opened_Date__c, noOfDaysToBreach , mySLA.Working_Days__c, upcomingHolidayDates);
                        myCase.Case_Expected_Escalation_Date__c = UtilityDateMethods.forecastFutureEventDate(myCase.Opened_Date__c, noOfDaysToEsc , mySLA.Working_Days__c, upcomingHolidayDates);
                    }
                         
                 	// If Status is On-hold need to set these fields blank
                    if(myCase.Status == 'On Hold')
                    {
                        myCase.Case_Expected_Breach_Date__c = null;
                        myCase.Case_Expected_Escalation_Date__c = null;
                    }
                }
            // Display error message if invalid match on SLA
            if (MatchingSLAs == 0)
                myCase.addError(' SLA \'' + myCase.Active_SLA__c + '\' not found. Please either select another SLA, no SLA, or contact the system administrator.');
            if (MatchingSLAs > 1)
                myCase.addError(' Multiple SLAs matched on \'' + myCase.Active_SLA__c + '\'. Please either select another SLA, no SLA, or contact the system administrator.');
        }
    }  
}