SourceMetaData/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>REP_Customer_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</description>
        <inlineHelpText>If the customer is not representing themselves for this case who has reported this case on behalf of the customer</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Goals</relationshipLabel>
        <relationshipName>Representing</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer who has reported the case that this record is a child of</description>
        <inlineHelpText>The customer who has reported the case that this record is a child of</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The CRM Case that the ticket is related to.</description>
        <inlineHelpText>The CRM Case that the ticket  is related to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer&apos;s representative (set on the case record)</description>
        <inlineHelpText>The customer&apos;s representative (set on the case record)</inlineHelpText>
        <label>Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Representing Customers on Tickets</relationshipLabel>
        <relationshipName>Tickets_Acting_as_Representative_on</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/UpdateTicketContacts.cls
/*------------------------------------------------------------
Author:        Ana Lomibao
Company:       Arcus Global Ltd
Date:          October 2013
Description:   Class that implements TicketWorkFlow, used on workflow class to update the contact references of the tickets based on the same contact references of case object
				
------------------------------------------------------------*/
public with sharing class UpdateTicketContacts implements TicketWorkFlow 
{
	public List<Ticket__c> applicableTickets;
	
	public UpdateTicketContacts()
	{
	}
	
	public void setApplicableTickets(Map<Id, Ticket__c> oldTickets, Map<Id, Ticket__c> newTickets, Boolean isUpdate, Boolean isInsert)
	{
		// WF triggered from Case object
		applicableTickets= newTickets.values();
	}
	
	public void applyWFToTickets()
	{
		for (Ticket__c t: applicableTickets)
		{
			if (t.GLOBAL_Customer__c != t.GLOBAL_Goal__r.ContactId)
				t.GLOBAL_Customer__c= t.GLOBAL_Goal__r.ContactId;
			
			if (t.GLOBAL_Representative__c != t.GLOBAL_Goal__r.REP_Customer_Representative__c)
				t.GLOBAL_Representative__c= t.GLOBAL_Goal__r.REP_Customer_Representative__c;
		}
		
		try
		{
			update applicableTickets;
		}catch (Exception e)
		{
			throw e;
		}
	}
	
}