SourceMetaData/src/objects/Confirm_Service_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>For use with the confirm integration</description>
    <fields>
        <fullName>Service_Code__c</fullName>
        <description>Confirm service code</description>
        <inlineHelpText>Confirm service code</inlineHelpText>
        <label>Service Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Description__c</fullName>
        <description>Confirm Service Description</description>
        <inlineHelpText>Confirm Service Description</inlineHelpText>
        <label>Service Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subject_Code__c</fullName>
        <description>Confirm subject code (required, unique)</description>
        <inlineHelpText>Confirm subject code (required, unique)</inlineHelpText>
        <label>Subject Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Confirm Service Codes</label>
</CustomObject>

SourceMetaData/src/objects/Confirm_Site_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>For use with the Confirm webservices integration</description>
    <fields>
        <fullName>Site_Code__c</fullName>
        <description>The site code of the location.</description>
        <inlineHelpText>A string describing the location of the site code</inlineHelpText>
        <label>Site Code</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Confirm Site Codes</label>
</CustomObject>

SourceMetaData/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Correspondence_Address__c</fullName>
        <formula>Account.Current_Correspondence_Address__c</formula>
        <inlineHelpText>Contact&apos;s current correspondence address.</inlineHelpText>
        <label>Primary Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Postcode__c</fullName>
        <description>The postcode of the persons primary address. Set only by workflow</description>
        <inlineHelpText>Primary address postcode</inlineHelpText>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

SourceMetaData/src/objects/External_ID__c.object
<CustomObject>
    <description>List of external ID references against tickets. e.g. a ticket may want to reference a particular record in a 3rd party environmental system.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <inlineHelpText>System to reference.</inlineHelpText>
        <label>External System</label>
        <picklist>
            <picklistValues>
                <fullName>Confirm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iBuild</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iPlan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iWorld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lagan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ohms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sostenuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trio/Protocol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebPay</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ticket__c</fullName>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipLabel>External IDs</relationshipLabel>
        <relationshipName>External_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>External ID</label>
    <nameField>
        <displayFormat>Ext{000000}</displayFormat>
        <label>External ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Target__c.object
<CustomObject>
    <description>The target of a ticket is the thing that the ticket is about. It will have different record types for different classes of target (eg address/ person/ account)</description>
    <fields>
        <fullName>Address_Street__c</fullName>
        <formula>Address__r.Street_Description__c</formula>
        <label>Street Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Correspondence_Address__c</fullName>
        <formula>SUBSTITUTE(Contact__r.Account.Current_Correspondence_Address__c,&apos;,&apos;,BR())</formula>
        <label>Current Primary Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket__c</fullName>
        <description>The Ticket that the target is related to</description>
        <inlineHelpText>The Ticket that the target is related to</inlineHelpText>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipLabel>Target</relationshipLabel>
        <relationshipName>Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Target</label>
    <nameField>
        <displayFormat>Tar{00000000}</displayFormat>
        <label>Target Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>The target is a customer or a contact</description>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>The target is a geographical location (address, street or area)</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer_Id__c</fullName>
        <description>For use when identifying customer ID from a ticket.</description>
        <formula>GLOBAL_Goal__r.Contact.Id</formula>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HHW_Enquiry_Description__c</fullName>
        <description>More details about the problem (optional)</description>
        <inlineHelpText>More details about the problem (optional)</inlineHelpText>
        <label>Enquiry Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Hounslow_Borough__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If enquiry is not about a specific location, or you cannot find street name, please check the box &apos;Hounslow Borough&apos;. Otherwise leave unchecked and specify Location in Target.</description>
        <inlineHelpText>If enquiry is not about a specific location, or you cannot find street name, please check the box &apos;Hounslow Borough&apos;. Otherwise leave unchecked and specify Location in Target.</inlineHelpText>
        <label>Hounslow Borough</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HHW_Location_Details__c</fullName>
        <description>Free-text location details used in Highways enquiries</description>
        <inlineHelpText>If enquiry is not about a specific location, or you cannot find the street name, please select &apos;Hounslow Borough&apos;. Enter more details about the location.</inlineHelpText>
        <label>Location Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HHW_Service__c</fullName>
        <description>Highways Service Area</description>
        <inlineHelpText>Highways Service Area</inlineHelpText>
        <label>Highways Service</label>
        <picklist>
            <picklistValues>
                <fullName>Drainage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Kerb Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ironwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licence Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Lights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Signs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traffic Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trees, Shrubs &amp; Vegetation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HHW_Subcategory__c</fullName>
        <description>A list of standard enquiries of Hounslow Homes</description>
        <inlineHelpText>Select a matching topic or General Enquiry</inlineHelpText>
        <label>Highways Sub-category</label>
        <picklist>
            <controllingField>HHW_Service__c</controllingField>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Smell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Drop Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freedom Of Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged/ Cracked Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Licence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Opportunities &amp; Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage To Pedestrian Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fault On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstruction On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Ice, Snow And Frost On Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Pothole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction (unauthorised)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spillage On Network (spillage On Road/footway/footpath)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streetlight/bollard Knocked Down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Dropped Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Shop Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Skip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uneven Footway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Animal On A Road Or Footpath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dog Fouling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/ConfirmConnector.cls
/*------------------------------------------------------------
Author:        Tony Evans 
Company:       Arcus Global Ltd
Date:          26/07/2013
Description:   Send to Confirm
Test Class:    
------------------------------------------------------------*/
public class ConfirmConnector
{
 	
    private boolean testFlag;
    
    public ConfirmConnector (boolean testFlag)
    {
        this.testFlag = testFlag;
    }
    
    /** (ANA) DEPRECATE THIS FUNCTION 
    public String ConfirmConnectorStart (Ticket__c confirmTicket) {
        String response = 'ERROR';
        Map<String,String> targetMap = new Map<String,String>{};
        
        // if not borough ticket get the target
        if (confirmTicket.HHW_Hounslow_Borough__c != true ){
        	// $$$$ Need to change this as will error if its a borough only ticket $$$$$
       		List<Target__c> targetList = [SELECT Ticket__c, Address_Street__c FROM Target__c 
                                          WHERE Ticket__r.Id =: confirmTicket.Id];
     		//Create a map between the ticket Id and the Street address of its target
        	for(Target__c target: targetList){
				targetMap.put(target.Ticket__c,target.Address_Street__c);
        	}        
        } else {
            targetMap.put(confirmTicket.Id,'Borough of Hounslow');
        }
        
        Map<String, Confirm_Site_Codes__c> siteCodes = Confirm_Site_Codes__c.getAll(); 
        
        List<Confirm_Service_Codes__c> serviceList = [SELECT Service_Description__c, Subject_Code__c, Service_Code__c FROM Confirm_Service_Codes__c];
     	
     	//Create information on filling service codes
		Map<String,String> serviceMap = new Map<String,String>{};
        for(Confirm_Service_Codes__c service: serviceList){
			serviceMap.put(service.Service_Description__c, service.Service_Code__c+':'+service.Subject_Code__c);
        }           
             
        response = sendToConfirm(confirmTicket,serviceMap, siteCodes, targetMap);
        //response = '1234';
        return response;
    }
    */
    
    public ServerResponseObject ConfirmConnectorStart2 (Ticket__c confirmTicket) 
    {
    	ServerResponseObject servRes= new ServerResponseObject();
        //String response = 'ERROR';
        
        Map<String,String> targetMap = new Map<String,String>{};
        // if not borough ticket get the target
        if (confirmTicket.HHW_Hounslow_Borough__c != true )
        {
        	// $$$$ Need to change this as will error if its a borough only ticket $$$$$
       		List<Target__c> targetList = [SELECT Ticket__c, Address_Street__c FROM Target__c 
                                          WHERE Ticket__r.Id =: confirmTicket.Id];
     		//Create a map between the ticket Id and the Street address of its target
        	for(Target__c target: targetList)
        	{
				targetMap.put(target.Ticket__c, target.Address_Street__c);
        	}        
        }else 
        {
            targetMap.put(confirmTicket.Id,'Borough of Hounslow');
        }
        
        Map<String, Confirm_Site_Codes__c> siteCodes = Confirm_Site_Codes__c.getAll(); 
        
        List<Confirm_Service_Codes__c> serviceList = [SELECT Service_Description__c, Subject_Code__c, Service_Code__c FROM Confirm_Service_Codes__c];
     	
     	//Create information on filling service codes
		Map<String,String> serviceMap = new Map<String,String>{};
        for(Confirm_Service_Codes__c service: serviceList){
			serviceMap.put(service.Service_Description__c, service.Service_Code__c + ':' + service.Subject_Code__c);
        }           
             
        servRes = sendToConfirm2(confirmTicket,serviceMap, siteCodes, targetMap);
        return servRes;
    }    

    /** (ANA) DEPRECATE THIS FUNCTION    
    public String sendToConfirm (Ticket__c myTicket, Map<String, String> serviceMap, Map<String, Confirm_Site_Codes__c> siteCodes, Map<String,String> targetMap) {
        String response = 'ERROR  sendToConfirm';
        System.debug('******** INFO: Sending to Confirm');
        ConfirmConnectorWrapper confirmConnection = new ConfirmConnectorWrapper();
        confirmConnection.EnquiryNumber = '1';        
        System.debug('******** INFO: Confirm - Processing Service ');
        // Set everything related to the service's
        String serviceDescString = myTicket.HHW_Service__c +' - '+ myTicket.HHW_Subcategory__c;
        String serviceCodeString = serviceMap.get(serviceDescString);
        if (serviceCodeString != null){
        	confirmConnection.ServiceCode = serviceCodeString.split(':',0)[0];
        	confirmConnection.SubjectCode = serviceCodeString.split(':',0)[1];
        }
        if (myTicket.HHW_Enquiry_Description__c != null){
        	confirmConnection.EnquiryDescription = myTicket.HHW_Enquiry_Description__c ;
        }
        // Set the fields related to location
        System.debug('******** INFO: Confirm - Processing Location ');
        if (myTicket.HHW_Hounslow_Borough__c == true ){
        	confirmConnection.SiteCode = '99999999';	
        } else {
            String AddressString = targetMap.get(myTicket.Id);
            if (AddressString != null){                
        		Confirm_Site_Codes__c siteCode = siteCodes.get(AddressString);
                if (siteCode != null){              
                    String siteCodeString = siteCode.Site_Code__c.toPlainString();            	          		
                    confirmConnection.SiteCode = siteCodeString;    
            	} else {
            		confirmConnection.SiteCode = '99999999';
            	}
            } else {
            	confirmConnection.SiteCode = '99999999';
            }
        }
        if (myTicket.HHW_Location_Details__c != null){
        	confirmConnection.EnquiryLocation = myTicket.HHW_Location_Details__c;
        }
        
        createCustomerFragment(myTicket, confirmConnection);       
        // see if its a test case
        confirmConnection.testFlag = testFlag;
        //Invoke Confirm    
        response = confirmConnection.sendConfirmSOAP();
        //response = '13579';
        return response;
    }
    */

    public ServerResponseObject sendToConfirm2 (Ticket__c myTicket, Map<String, String> serviceMap, Map<String, Confirm_Site_Codes__c> siteCodes, Map<String,String> targetMap) 
    {
        ServerResponseObject response= new ServerResponseObject();
        ConfirmConnectorWrapper confirmConnection = new ConfirmConnectorWrapper();
        confirmConnection.EnquiryNumber = '1';
                
        // Set everything related to the service's
        String serviceDescString = myTicket.HHW_Service__c + ' - ' + myTicket.HHW_Subcategory__c;
        String serviceCodeString = serviceMap.get(serviceDescString);
        if (serviceCodeString != null)
        {
        	confirmConnection.ServiceCode = serviceCodeString.split(':',0)[0];
        	confirmConnection.SubjectCode = serviceCodeString.split(':',0)[1];
        }else
        {
        	response.success= false;
        	response.response= 'Please contact your administrator to provide a Service Code in the custom settings for the following service: ' + serviceDescString;
        	return response;
        }
        
        if (myTicket.HHW_Enquiry_Description__c != null)
        {
        	confirmConnection.EnquiryDescription = myTicket.HHW_Enquiry_Description__c ;
        }
        
        // Set the fields related to location
        System.debug('******** INFO: Confirm - Processing Location ');
        if (myTicket.HHW_Hounslow_Borough__c == true )
        {
        	confirmConnection.SiteCode = '99999999';	
        } else 
        {
            String AddressString = targetMap.get(myTicket.Id);
            if (AddressString != null)
            {                
        		Confirm_Site_Codes__c siteCode = siteCodes.get(AddressString);
                if (siteCode != null)
                {              
                    String siteCodeString = siteCode.Site_Code__c.toPlainString();            	          		
                    confirmConnection.SiteCode = siteCodeString;    
            	} else 
            	{
            		confirmConnection.SiteCode = '99999999';
            	}
            } else 
            {
            	confirmConnection.SiteCode = '99999999';
            }
        }

        if (myTicket.HHW_Location_Details__c != null)
        {
        	confirmConnection.EnquiryLocation = myTicket.HHW_Location_Details__c;
        }
        
        if (String.isNotBlank(myTicket.GLOBAL_Customer_Id__c))
        {
        	createCustomerFragment(myTicket, confirmConnection);
        }else
        {
			response.success= false;
			response.response= 'The ticket needs customer information in order to confirm.';
			return response;        	
        }       
        
        // see if its a test case
        confirmConnection.testFlag = testFlag;
        
        //Invoke Confirm    
        response = confirmConnection.sendConfirmSOAP2();
        return response;
    }
    
    private void createCustomerFragment (Ticket__c myTicket, ConfirmConnectorWrapper confirmConnection){
        System.debug('******** INFO: Processing Customer');
        Contact customer = new Contact();
        customer = [SELECT Id, Salutation, FirstName, LastName, HomePhone, MobilePhone, OtherPhone, Email,
                   Current_Correspondence_Address__c, Primary_Address_Postcode__c
                  FROM Contact 
                  WHERE (Id=:myTicket.GLOBAL_Customer_Id__c)][0];
                  
        confirmConnection.CustomerTitle = customer.Salutation;
        confirmConnection.CustomerForename = customer.FirstName;
       	confirmConnection.CustomerSurname = customer.LastName;
        if (customer.HomePhone != null) {
            confirmConnection.CustomerPhone = customer.HomePhone;
        } else if (customer.MobilePhone != null) {
            confirmConnection.CustomerPhone = customer.MobilePhone;
        } else if (customer.OtherPhone != null) {
            confirmConnection.CustomerPhone = customer.OtherPhone;
        }
        confirmConnection.CustomerEmail = customer.Email;
       
        //Process address
        if (customer.Current_Correspondence_Address__c != null)
        {
        	String customerAddr = customer.Current_Correspondence_Address__c;	       
            if (customerAddr.contains(','))
            {
            }
        }
        if (customer.Primary_Address_Postcode__c != null)
        {
        	confirmConnection.CustomerPostCode = customer.Primary_Address_Postcode__c;	
        }
    }
    
    public void addExternalID(String confirmTicket, String externalID)
    {
        External_ID__c externalIDObject = new External_ID__c();
        externalIDObject.Ticket__c = confirmTicket;
        externalIDObject.External_System__c = 'Confirm';
        externalIDObject.External_ID__c = externalID;
        insert externalIDObject;
    }

}