SourceMetaData/src/objects/SLA__c.object
<CustomObject>
    <description>A record of the available SLAs that can be applied to Goals and Tickets</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the SLA currently active</description>
        <inlineHelpText>Is the SLA currently active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>An optional description of the SLA (eg to describe what it is used for)</description>
        <inlineHelpText>An optional description of the SLA (eg to describe what it is used for)</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Prior_to_SLA_Breach_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If the record should be escalated a set number of days prior to SLA breach (assuming it hasn&apos;t already been escalated or closed) then specify the number of days before the SLA breach that the record should be escalated here. (0 = no auto escalation required)</description>
        <inlineHelpText>The number of days before the SLA breach that the record should be escalated here. (0 = escalation required)</inlineHelpText>
        <label>Escalation Prior to SLA Breach (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA_Length_Days__c</fullName>
        <description>The length of the SLA in days</description>
        <label>SLA Length (Days)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working_Days__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked if the SLA is measured in working days, unchecked if it is measured in calendar days.</description>
        <inlineHelpText>Checked if the SLA is measured in working days, unchecked if it is measured in calendar days.</inlineHelpText>
        <label>Working Days</label>
        <type>Checkbox</type>
    </fields>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 2 - Chidlren&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Children&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Adult&apos;s Social Care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Calendar_Days_Elapsed__c</fullName>
        <description>Number of calendar days during which the Ticket was opened or escalated</description>
        <inlineHelpText>Number of calendar days during which the Ticket was opened or escalated</inlineHelpText>
        <label>Calendar Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Closed_Date__c</fullName>
        <inlineHelpText>Ticket was closed on this date (blank for not-closed ticket)</inlineHelpText>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Feedback_Cutoff_Date__c</fullName>
        <description>The latest date at which the customer cna provide feedback or request that a closed ticket is re-opened</description>
        <inlineHelpText>The latest date at which the customer cna provide feedback or request that a closed ticket is re-opened (3 working days after closed date)</inlineHelpText>
        <label>Feedback Cutoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Opened_Date__c</fullName>
        <description>The date that the ticket was opened (Start of SLA countdown)</description>
        <inlineHelpText>Ticket status was changed to Open on this date. (Start of SLA countdown)</inlineHelpText>
        <label>Opened Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ticket SLA requirements.</description>
        <inlineHelpText>Ticket SLA requirements.</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Expected_Breach_Date__c</fullName>
        <description>The date at which the ticket is forecasted to be in breach of its SLA</description>
        <inlineHelpText>The date at which the ticket is forecasted to be in breach of its SLA</inlineHelpText>
        <label>Expected Breach Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Expected_Escalation_Date__c</fullName>
        <description>The date at which the ticket is forecasted to be escalated as it is nearing breach of its SLA</description>
        <inlineHelpText>The date at which the ticket is forecasted to be escalated as it is nearing breach of its SLA</inlineHelpText>
        <label>Expected Escalation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Working_Days_Elapsed__c</fullName>
        <description>Number of working days during which the Ticket was opened or escalated</description>
        <inlineHelpText>Number of working days during which the Ticket was opened or escalated</inlineHelpText>
        <label>Working Days Elapsed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/trigger_Ticket_SLA.cls
/*------------------------------------------------------------
Author:        Matt Urbanowski
Company:       Arcus Global Ltd
Date:          26/07/2013
Description:   Takes the value in SLA picklist and assigns it the relevant lookup value from the SLA object.
Test Class:    SLATestClass
------------------------------------------------------------*/
public class trigger_Ticket_SLA {
    
    public trigger_Ticket_SLA(Ticket__c[] newTickets) {
        
        // SOQL ------
        // Get list of all SLA lookups
        List<SLA__c> SLAs = [Select Id, Name, Description__c, Working_Days__c, Escalation_Prior_to_SLA_Breach_Days__c, SLA_Length_Days__c from SLA__c where Active__c=true];
        // Get list of upcoming Holidays, then add all holiday dates to a set of dates
        Set<Date> upcomingHolidayDates = UtilityDateMethods.GetUpcomingHolidayDates();
        // ---- End of SOQL
        
        Integer noOfDaysToBreach;
        Integer noOfDaysToEsc;
        
        for (Ticket__c myTicket : newTickets) 
        {
    		system.debug('******************* trigger_Ticket_SLA, myTicket.GLOBAL_Ticket_Status__c= ' + myTicket.GLOBAL_Ticket_Status__c);
            Integer MatchingSLAs = 0;
            
            if (myTicket.GLOBAL_Active_SLA__c == null) 
            {  
            	// Blank SLA
                myTicket.GLOBAL_Ticket_Expected_Breach_Date__c = null;
                myTicket.GLOBAL_Ticket_Expected_Escalation_Date__c = null;
                myTicket.GLOBAL_SLA__c = null;
                MatchingSLAs++;
            } else 
            {
                for (SLA__c mySLA : SLAs) // Find relevant SLA from lookup table and apply
                    if (myTicket.GLOBAL_Active_SLA__c == mySLA.Name) 
                    {
                        MatchingSLAs++;
                        myTicket.GLOBAL_SLA__c = mySLA.Id;
                        
                        // Now that an SLA has been matched need to update the expected escalation data and expected breach date fields on the object.
                        // Note that when calculating this it is NOT SAFE to use the myCase.SLA_Days_Remaining__c field as it is a formula field and will not have updated yet as a result of SLA change (before trigger preeceds it)
                        // Fields to use:
                        //Ticket: GLOBAL_Ticket_Status__c, GLOBAL_Opened_Date__c, GLOBAL_Calendar_Days_Elapsed__c, GLOBAL_Working_Days_Elapsed__c
                        //SLA: Working_Days__c, Escalation_Prior_to_SLA_Breach_Days__c,SLA_Length_Days__c
                        // Use these to calcualte the days of SLA that are left (and days left before escalation is required) and pass these to CalcEscOrBreachDate helper method. 
                        
                        noOfDaysToBreach = UtilityDateMethods.GetNoDaysTillBreach( mySLA, (Integer)myTicket.Global_Working_Days_Elapsed__c, (Integer)myTicket.GLOBAL_Calendar_Days_Elapsed__c);
                        noOfDaysToEsc = UtilityDateMethods.GetNoDaysTillEsc(mySLA, (Integer)myTicket.Global_Working_Days_Elapsed__c, (Integer)myTicket.GLOBAL_Calendar_Days_Elapsed__c);
                        
                        // Pass params to the funtion to set expected esc and breach dates
                        myTicket.Global_Ticket_Expected_Breach_Date__c = UtilityDateMethods.forecastFutureEventDate(myTicket.GLOBAL_Opened_Date__c, noOfDaysToBreach , mySLA.Working_Days__c, upcomingHolidayDates);
                        myTicket.Global_Ticket_Expected_Escalation_Date__c = UtilityDateMethods.forecastFutureEventDate(myTicket.GLOBAL_Opened_Date__c, noOfDaysToEsc , mySLA.Working_Days__c, upcomingHolidayDates);
                        system.debug('************************** myTicket.Global_Ticket_Expected_Breach_Date__c= ' + myTicket.Global_Ticket_Expected_Breach_Date__c);
                    }
                // If Status is On-hold need to set these fields blank
                if(myTicket.GLOBAL_Ticket_Status__c == 'On Hold')
                {
                    myTicket.GLOBAL_Ticket_Expected_Breach_Date__c = null;
                    myTicket.GLOBAL_Ticket_Expected_Escalation_Date__c = null;
                }
                // else if the ticket is closed set the feedback cutoff date to 3 working days after the closed date
                // TODO do this just for ICT related tickets? 
                // TODO Not hardcode in the 3 working days element here. 
                else if (myTicket.GLOBAL_Ticket_Status__c == 'Closed' )
                {
	                system.debug('******* setting myTicket.GLOBAL_Ticket_Status__c');
                    myTicket.GLOBAL_Feedback_Cutoff_Date__c  = UtilityDateMethods.forecastFutureEventDate(myTicket.GLOBAL_Closed_Date__c, 3 , true, upcomingHolidayDates);
                    system.debug('********** check this ' + myTicket.GLOBAL_Feedback_Cutoff_Date__c);
                }
            }
            
            // Display error message if invalid match on SLA
            if (MatchingSLAs == 0)
                myTicket.addError(' SLA \'' + myTicket.GLOBAL_Active_SLA__c + '\' not found. Please either select another SLA, no SLA, or contact the system administrator.');
            if (MatchingSLAs > 1)
                myTicket.addError(' Multiple SLAs matched on \'' + myTicket.GLOBAL_Active_SLA__c + '\'. Please either select another SLA, no SLA, or contact the system administrator.');
        }
    }
}