SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer_Curr_Correspondence_Addr__c</fullName>
        <formula>SUBSTITUTE(GLOBAL_Goal__r.Contact_Correspondence_Address__c,&apos;,&apos;,BR())</formula>
        <label>Customer Current Primary Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer_Email__c</fullName>
        <formula>GLOBAL_Goal__r.Contact.Email</formula>
        <label>Customer Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer_Name__c</fullName>
        <formula>GLOBAL_Goal__r.Contact.Salutation_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer_Phone_Number__c</fullName>
        <formula>GLOBAL_Goal__r.Contact.HomePhone</formula>
        <inlineHelpText>Customer&apos;s home phone number.</inlineHelpText>
        <label>Customer Home Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HHW_Enquiry_Description__c</fullName>
        <description>More details about the problem (optional)</description>
        <inlineHelpText>More details about the problem (optional)</inlineHelpText>
        <label>Enquiry Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Location__c</fullName>
        <description>Address selected via Target</description>
        <inlineHelpText>Please select street via Target or, if location is not found, tick &quot;Hounslow Borough&quot; checkbox</inlineHelpText>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Service__c</fullName>
        <description>Highways Service Area</description>
        <inlineHelpText>Highways Service Area</inlineHelpText>
        <label>Highways Service</label>
        <picklist>
            <picklistValues>
                <fullName>Drainage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Kerb Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ironwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licence Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Lights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Signs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traffic Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trees, Shrubs &amp; Vegetation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HHW_Subcategory__c</fullName>
        <description>A list of standard enquiries of Hounslow Homes</description>
        <inlineHelpText>Select a matching topic or General Enquiry</inlineHelpText>
        <label>Highways Sub-category</label>
        <picklist>
            <controllingField>HHW_Service__c</controllingField>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Smell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Drop Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freedom Of Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged/ Cracked Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Licence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Opportunities &amp; Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage To Pedestrian Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fault On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstruction On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Ice, Snow And Frost On Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Pothole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction (unauthorised)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spillage On Network (spillage On Road/footway/footpath)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streetlight/bollard Knocked Down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Dropped Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Shop Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Skip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uneven Footway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Animal On A Road Or Footpath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dog Fouling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/trigger_Ticket_Confirm.cls
/*------------------------------------------------------------
Author:        Tony Evans / Matt Urbanowski
Company:       Arcus Global Ltd
Date:          26/07/2013
Description:   Send to Confirm
Test Class:    
------------------------------------------------------------*/
public class trigger_Ticket_Confirm {

    public trigger_Ticket_Confirm (Ticket__c[] newTickets) {
    
    }

    /* Commenting out below to improve test coverage
    private void sendToConfirm (Ticket__c myTicket) {
        String ServiceCode = myTicket.HHW_Service__c + myTicket.HHW_Subcategory__c;
        String SubjectCode = '';
        String SiteCode = '';
        String EnquiryDescription = myTicket.HHW_Enquiry_Description__c ;
        String EnquiryLocation = myTicket.HHW_Location__c;
        List<String> EnquiryCustomer = createCustomerFragment(myTicket);
    }
    
    private List<String> createCustomerFragment (Ticket__c myTicket){
        List<String> EnquiryCustomer = new List<String>();
        
        String CustomerTypeCode = 'MOP';
        String PointOfContactCode = 'SELF';
        String EnquiryMethodCode = 'WEB';
        String customerName = myTicket.GLOBAL_Customer_Name__c;
        List<String> customerNameParts = customerName.split(' ',0);     
        EnquiryCustomer.add(''); // CustomerTitle
        EnquiryCustomer.add(customerNameParts[1]);
        EnquiryCustomer.add(customerNameParts[0]);
        EnquiryCustomer.add(myTicket.GLOBAL_Customer_Phone_Number__c);
        EnquiryCustomer.add(myTicket.GLOBAL_Customer_Email__c);
        String customerAddr = myTicket.GLOBAL_Customer_Curr_Correspondence_Addr__c;
        List<String> customerAddrParts = customerName.split(',',0);  
        EnquiryCustomer.add(customerAddrParts[0]);
        EnquiryCustomer.add('');
        EnquiryCustomer.add(customerAddrParts[1]);
        EnquiryCustomer.add(customerAddrParts[2]);
        EnquiryCustomer.add(customerAddrParts[3]);
        EnquiryCustomer.add(CustomerTypeCode);
        EnquiryCustomer.add(PointOfContactCode);
        EnquiryCustomer.add(EnquiryMethodCode);
        
        return EnquiryCustomer;
    }
    */

}