SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Opened_Date__c</fullName>
        <description>The date that the ticket was opened (Start of SLA countdown)</description>
        <inlineHelpText>Ticket status was changed to Open on this date. (Start of SLA countdown)</inlineHelpText>
        <label>Opened Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/SetOpenedDate.cls
public with sharing class SetOpenedDate 
{
	public SetOpenedDate()
	{
	}
	
	// This method sets Opened Date to Today when a ticket status' is set to Open
	public void setOpenedDatToTickets(List<Ticket__c> oldTickets, List<Ticket__c> newTickets)
	{
		if (oldTickets == null)
		{
			// inserting new tickets
			for (Ticket__c t: newTickets)
			{
				if (t.GLOBAL_Ticket_Status__c.compareTo('Open') == 0)
					t.GLOBAL_Opened_Date__c= Date.today();
			}
		}else
		{
			// updating tickets
			Map<Id, Ticket__c> oldTicketsMap= new Map<Id, Ticket__c>();
			oldTicketsMap.putAll(oldTickets); 
			for (Ticket__c t: newTickets)
			{
				if (t.GLOBAL_Ticket_Status__c.compareTo('Open') == 0 
					&& oldTicketsMap.get(t.Id) != null && oldTicketsMap.get(t.Id).GLOBAL_Ticket_Status__c.compareTo('Open') != 0)
					t.GLOBAL_Opened_Date__c= Date.today();
			}
		}
	}
	
}