SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>CMP_Manual_Resolution_Date_Agreed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if a Manual Resolution Date has been agreed</description>
        <inlineHelpText>Checked if a Manual Resolution Date has been agreed</inlineHelpText>
        <label>Manual Resolution Date Agreed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Active_SLA__c</fullName>
        <description>A list of the current active SLAs that can be applied to this record</description>
        <inlineHelpText>A list of the current active SLAs that can be applied to this record</inlineHelpText>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>2 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Working Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 Calendar Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Working Days (1 Day Escalation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 2 - Chidlren&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Children&apos;s Social Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stage 1 - Adult&apos;s Social Care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GLOBAL_SLA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ticket SLA requirements.</description>
        <inlineHelpText>Ticket SLA requirements.</inlineHelpText>
        <label>SLA Lookup</label>
        <referenceTo>SLA__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/SetManualResolutionDateController.cls
public class SetManualResolutionDateController {

    public Ticket__c myTicket {get; set;}
    private Apexpages.StandardController scon;
    public boolean disableSave {get; set;}

    public SetManualResolutionDateController(ApexPages.StandardController controller) {
        scon = controller;
        scon.addFields(new List<String> {'GLOBAL_SLA__c', 'GLOBAL_Active_SLA__c','CMP_Manual_Resolution_Date_Agreed__c','GLOBAL_Ticket_Status__c' });
        myTicket = (Ticket__c)controller.getRecord();
        // if a manual resolution date has already been agreed it is not allowed to define another. Disable the save button.
        disableSave = false;
        if (myTicket.CMP_Manual_Resolution_Date_Agreed__c){
            disableSave = true;
        }
    }
    
    public PageReference save() {
        //Save Button clicked. Save the record and return to it. 
        myTicket.CMP_Manual_Resolution_Date_Agreed__c = true;
        myTicket.GLOBAL_SLA__c = null;
        myTicket.GLOBAL_Active_SLA__c = null;
        myTicket.GLOBAL_Ticket_Status__c = 'Open';
        
        // try to save the record, if it saves ok return to ticket otherwise display error
        PageReference pr;
        try{
            pr = scon.save();
        }
        catch(Exception e) {
            throw e;
        }
        
        if (pr != null){
            pr.setRedirect(true);
        }
        return pr;
    }

}