SourceMetaData/src/objects/Ticket__c.object
<CustomObject>
    <description>An object that is used to store individual tickets linked to a goal (case).</description>
    <fields>
        <fullName>GLOBAL_Customer_Id__c</fullName>
        <description>For use when identifying customer ID from a ticket.</description>
        <formula>GLOBAL_Goal__r.Contact.Id</formula>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Customer_Name__c</fullName>
        <formula>GLOBAL_Goal__r.Contact.Salutation_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLOBAL_Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#AFCADF</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
                <color>#CC66CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>SLA Breach</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#33CC00</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HHW_Enquiry_Description__c</fullName>
        <description>More details about the problem (optional)</description>
        <inlineHelpText>More details about the problem (optional)</inlineHelpText>
        <label>Enquiry Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Hounslow_Borough__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If enquiry is not about a specific location, or you cannot find street name, please check the box &apos;Hounslow Borough&apos;. Otherwise leave unchecked and specify Location in Target.</description>
        <inlineHelpText>If enquiry is not about a specific location, or you cannot find street name, please check the box &apos;Hounslow Borough&apos;. Otherwise leave unchecked and specify Location in Target.</inlineHelpText>
        <label>Hounslow Borough</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HHW_Location_Details__c</fullName>
        <description>Free-text location details used in Highways enquiries</description>
        <inlineHelpText>If enquiry is not about a specific location, or you cannot find the street name, please select &apos;Hounslow Borough&apos;. Enter more details about the location.</inlineHelpText>
        <label>Location Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HHW_Location__c</fullName>
        <description>Address selected via Target</description>
        <inlineHelpText>Please select street via Target or, if location is not found, tick &quot;Hounslow Borough&quot; checkbox</inlineHelpText>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HHW_Service__c</fullName>
        <description>Highways Service Area</description>
        <inlineHelpText>Highways Service Area</inlineHelpText>
        <label>Highways Service</label>
        <picklist>
            <picklistValues>
                <fullName>Drainage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Kerb Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ironwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licence Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Lights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Signs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traffic Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trees, Shrubs &amp; Vegetation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HHW_Subcategory__c</fullName>
        <description>A list of standard enquiries of Hounslow Homes</description>
        <inlineHelpText>Select a matching topic or General Enquiry</inlineHelpText>
        <label>Highways Sub-category</label>
        <picklist>
            <controllingField>HHW_Service__c</controllingField>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Smell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Drop Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freedom Of Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged/ Cracked Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Drain Or Man Hole Cover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apply For A Licence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Opportunities &amp; Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage To Pedestrian Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fault On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstruction On Public Right Of Way</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Ice, Snow And Frost On Roads &amp; Footpaths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Pothole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Obstruction (unauthorised)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spillage On Network (spillage On Road/footway/footpath)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streetlight/bollard Knocked Down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Dropped Kerb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Shop Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unauthorised Skip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uneven Footway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street Cleaning Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Animal On A Road Or Footpath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dog Fouling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T{00000000}</displayFormat>
        <label>Ticket Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <recordTypes>
        <fullName>Highways</fullName>
        <active>true</active>
        <description>Hounslow Highways (Field Prefix = HHW)</description>
        <label>Highways</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SourceMetaData/src/classes/ConfirmTicketControllerExtension.cls
/*------------------------------------------------------------
Author:        Tony Evans
Company:       Arcus Global Ltd
Date:          05/07/2013
Description:   Extension class used to manage the sending of tickets to Confirm 
Test Class:    TestClass
------------------------------------------------------------*/

public with sharing class ConfirmTicketControllerExtension
{
    
	private ServerResponseObject servRes;
	public Boolean testStatus {get; set;}
	public Ticket__c ticket {get; set;}
	public String serviceDesc {get; set;}
	
	public ConfirmTicketControllerExtension(Apexpages.StandardController scon)
	{
		testStatus = false;
		servRes= new ServerResponseObject();
		if (!Test.isRunningTest())
			scon.addFields(new List<String> 
								{	'HHW_Hounslow_Borough__c', 
								 	'HHW_Service__c', 
								 	'HHW_Subcategory__c', 
								 	'GLOBAL_Customer_Name__c',
	    							'GLOBAL_Ticket_Status__c', 
	    							'HHW_Location_Details__c', 
	    							'GLOBAL_Customer_Id__c', 
	    							'HHW_Location__c', 
	    							'HHW_Enquiry_Description__c'
								}
							);
		ticket= (Ticket__c)scon.getRecord();
		
		if (ticket.HHW_Service__c != null)
			serviceDesc = ticket.HHW_Service__c;
		if (ticket.HHW_Subcategory__c != null)
		{
			if (serviceDesc != null)
				serviceDesc= serviceDesc + ' - ';
			serviceDesc= serviceDesc + ticket.HHW_Subcategory__c;
		}
	}
	
    public Pagereference sendToConfirm()
    {        
        // call confirm class - get result
        ConfirmConnector connector = new ConfirmConnector(testStatus);
        ServerResponseObject response = connector.ConfirmConnectorStart2(ticket);
        
        ApexPages.Message msg;
		if (response.success)
		{
			msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Your ticket has been submittied to Hounslow Highways, the following ConfirmID has been added to the ticket= ' 
				+ response.response);
            connector.addExternalID(ticket.Id, response.response);
            ticket.GLOBAL_Ticket_Status__c = 'Closed';
            upsert ticket;			
		}else
		{
			msg = new ApexPages.Message(ApexPages.Severity.ERROR, response.response);
		}
		Apexpages.addMessage(msg);
        
		return null;
    }

}